# Generated by Django 3.1.7 on 2021-03-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='receivername',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='sendername',
            new_name='sender',
        ),
    ]
